apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-primary-config
  namespace:  sql
data:
  # SQL Server configuration
  ACCEPT_EULA: "Y"
  SA_PASSWORD: "K8sAdmin1234!"
  MSSQL_PID: "Developer"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-primary
  namespace: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-primary
  template:
    metadata:
      labels:
        app: sqlserver-primary
    spec:
      containers:
      - name: sqlserver-primary
        image: mcr.microsoft.com/mssql/server:2025-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: sqlserver-primary-config
              key: ACCEPT_EULA
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sqlserver-primary-config
              key: SA_PASSWORD
        - name: MSSQL_PID
          valueFrom:
            configMapKeyRef:
              name: sqlserver-primary-config
              key: MSSQL_PID
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-primary-service
  namespace: sql
spec:
  selector:
    app: sqlserver-primary
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
  type: ClusterIP
---
# External service for SSMS access
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-primary-external
  namespace: sql
spec:
  selector:
    app: sqlserver-primary
  ports:
  - name: sql
    port: 1433
    targetPort: 1433
    protocol: TCP
    nodePort: 31433  # External port for SSMS access - different from Docker port 1433
  type: NodePort
